# -*- coding: utf-8 -*-
"""Language_Translations_English-Hindi-Marathi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p2aWpWaWaPrRPqNlkQhuIAEABGEZPFVJ
"""

pip install googletrans==4.0.0-rc1

from googletrans import Translator

def translate_text():
    translator = Translator()

    print("Language Translator (English <-> Hindi <-> Marathi)")
    print("Type 'exit' to quit.")

    while True:
        print("\nChoose translation direction:")
        print("1. English to Hindi")
        print("2. English to Marathi")
        print("3. Hindi to English")
        print("4. Marathi to English")
        print("5. Hindi to Marathi")
        print("6. Marathi to Hindi")

        choice = input("Enter your choice (1, 2, 3, 4, 5, or 6): ").strip()

        if choice.lower() == 'exit':
            print("Exiting translator. Goodbye!")
            break

        if choice not in ['1', '2', '3', '4', '5', '6']:
            print("Invalid choice. Please enter 1, 2, 3, 4, 5, or 6.")
            continue

        text_to_translate = input("Enter the text to translate: ").strip()

        if text_to_translate.lower() == 'exit':
            print("Exiting translator. Goodbye!")
            break

        src_lang = ''
        dest_lang = ''
        original_lang_name = ''
        translated_lang_name = ''

        if choice == '1':
            src_lang = 'en'
            dest_lang = 'hi'
            original_lang_name = 'English'
            translated_lang_name = 'Hindi'
        elif choice == '2':
            src_lang = 'en'
            dest_lang = 'mr'
            original_lang_name = 'English'
            translated_lang_name = 'Marathi'
        elif choice == '3':
            src_lang = 'hi'
            dest_lang = 'en'
            original_lang_name = 'Hindi'
            translated_lang_name = 'English'
        elif choice == '4':
            src_lang = 'mr'
            dest_lang = 'en'
            original_lang_name = 'Marathi'
            translated_lang_name = 'English'
        elif choice == '5':
            src_lang = 'hi'
            dest_lang = 'mr'
            original_lang_name = 'Hindi'
            translated_lang_name = 'Marathi'
        elif choice == '6':
            src_lang = 'mr'
            dest_lang = 'hi'
            original_lang_name = 'Marathi'
            translated_lang_name = 'Hindi'

        try:
            translated = translator.translate(text_to_translate, src=src_lang, dest=dest_lang)
            print(f"\nOriginal ({original_lang_name}): {text_to_translate}")
            print(f"Translated ({translated_lang_name}): {translated.text}")
        except Exception as e:
            print(f"An error occurred during translation: {e}")
            print("Please check your internet connection or try again.")

if __name__ == "__main__":
    translate_text()